parameters:
  "service-dir":
    default: "sdk/contosowidgetmanager"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
options:
  "@azure-tools/typespec-csharp":
    namespace: "Azure.ResourceManager.ContosoWidgetManager"
  "@azure-tools/typespec-java":
    namespace: "com.azure.resourcemanager.contosowidgetmanager"
  "@azure-tools/typespec-python":
    namespace: "azure.mgmt.contosowidgetmanager"
  "@azure-tools/typespec-ts":
    package-details:
      name: "@azure/arm-contosowidgetmanager"
  "@azure-tools/typespec-go":
    module: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/contosowidgetmanager/armcontosowidgetmanager"